version: '3'

services:
  web:
    restart: unless-stopped
    image: jarischaefer/docker-librenms
    container_name: librenms
    ports:
      - "13521:80"
      - "13522:443"
    volumes:
      - /opt/vm-data/librenms/logs:/opt/librenms/logs
      - /opt/vm-data/librenms/rrd:/opt/librenms/rrd
    environment:
      - APP_KEY=base64:lFc4gIBkSZp0UsDqxjtTJ07nU/JSbJTl8jFwGGA2khRVdCWK7xAS6aszqGTpAgZGo0H/cB/bdlXEMp0Gfx43uw==
      - DB_HOST=db
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=secret
      - POLLERS=16
      - BASE_URL=/
      - TZ=Asia/Shanghai
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: mysql:5.6
    command: --sql-mode=""
    volumes:
      - /opt/vm-data/librenms-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
