version: '2'

services:
  web:
    restart: unless-stopped
    image: jarischaefer/docker-librenms
    container_name: librenms
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/vm-data/librenms/logs:/opt/librenms/logs
      - /opt/vm-data/librenms/rrd:/opt/librenms/rrd
    environment:
      - DB_HOST=db
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASS=secret
      - POLLERS=16
      - BASE_URL=http://192.168.163.19
      - TZ=Asia/Shanghai
    links:
      - mysql:db
  mysql:
    restart: unless-stopped
    image: mysql:5.6
    command: --sql-mode=""
    expose:
      - 3306
    volumes:
      - /opt/vm-data/librenms-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
